######################## custom scripts & styles ####################

# Add custom assets relative to /static or via https
logo_on_white: "/gcs_logo/logo.png"
logo_on_black: "/gcs_logo/logo-light.png"
custom_js: []
custom_css: []

######################## custom config ####################

### default social share image (can also be set per lang) ###
images: ["/img/social-share.png"]

github:
  repo_url: "https://github.com/username/repo/blob/master"
  show_edit_link: true

social_links:
  devstats: ""
  discord: ""
  facebook: "https://www.facebook.com/pages/Global-Commerce-and-Services-LLC/146101898738025"
  flickr: ""
  github: "https://github.com/rricks4/gcs_proto3"
  instagram: ""
  landscape: ""
  linkedin: "https://www.linkedin.com/company/global-commerce-and-services-llc"
  mastodon: ""
  pinterest: ""
  rss: ""
  slack: ""
  stackoverflow: ""
  threads: ""
  twitter: ""
  x: "https://x.com/globalcommserv"
  youtube: ""

# Makes the header sticky on tall screens
sticky_header: true
# Enable search in header UI
show_search: true
